import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import LayoutUi from "@/components/LayoutUi";
import AdvertiseLayout from "@/components/AdvertiseLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flight Site",
  description: "Generated by Amir Seraj",
  icons: {
    icon: [
      {
        url: "/favicon.ico",
        href: "/favicon.ico",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdvertiseLayout>
          <Header />
          <div className="xl:px-80 sm:px-10 px-4 pb-16 pt-10 screen">
            <LayoutUi>{children}</LayoutUi>
          </div>
          <Footer />
        </AdvertiseLayout>
      </body>
    </html>
  );
}
